# Generated by Django 4.2.3 on 2023-08-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson4', '0002_advertisment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(default=1, upload_to='lesson4/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
